import os
import shutil
import subprocess


def run(rel_filename, working_dir):
    """ Rebuild the files autogenerated from SBML files

    * MATLAB
    * Octave
    * XPP

    Args:
        rel_filename (:obj:`str`): relative filename
        working_dir (:obj:`str`): directory of entries to change (e.g., ``final``, ``original``)
    """
    sbml_filename = os.path.join(working_dir, rel_filename)

    # BioPAX L2
    subprocess.check_call(['sbfConverter.sh', 'SBMLModel', 'SBML2BioPAX_l2', sbml_filename])
    biopax_filename = sbml_filename.replace('.xml', '-biopax2.owl')
    if biopax_filename.endswith('_url-biopax2.owl'):
        shutil.move(biopax_filename, biopax_filename.replace('_url-biopax2.owl', '-biopax2.owl'))

    # BioPAX L3
    subprocess.check_call(['sbfConverter.sh', 'SBMLModel', 'SBML2BioPAX_l3', sbml_filename])
    biopax_filename = sbml_filename.replace('.xml', '-biopax3.owl')
    if biopax_filename.endswith('_url-biopax3.owl'):
        shutil.move(biopax_filename, biopax_filename.replace('_url-biopax3.owl', '-biopax3.owl'))

    # MATLAB
    subprocess.check_call(['sbfConverter.sh', 'SBMLModel', 'SBML2Octave', sbml_filename])
    matlab_filename = sbml_filename.replace('.xml', '.m')
    if matlab_filename.endswith('_url.m'):
        shutil.move(matlab_filename, matlab_filename.replace('_url.m', '.m'))

    # XPP
    subprocess.check_call(['sbfConverter.sh', 'SBMLModel', 'SBML2XPP', sbml_filename])
    xpp_filename = sbml_filename.replace('.xml', '.xpp')
    if xpp_filename.endswith('_url.xpp'):
        shutil.move(xpp_filename, xpp_filename.replace('_url.xpp', '.xpp'))
