# -*- coding: utf-8 -*-
from glob import glob
import os

def run(dirname: str):
    """
    Remove bad PDF files created by the Systems Biology Format Converter (SBFC)

    Args:
        dirname (:obj:`str`): the directory in which PDF files will be removed
    """
    for filename in glob(os.path.join(dirname, '**', '*.pdf'), recursive=True):
        is_file_good = True
        with open(filename, 'rb') as file:
            for line in file:
                if b'#Something went wrong' in line or b"We are sorry" in line:
                    is_file_good = False
                    break
        if not is_file_good:
            print(f'PDF file {filename} was not successfully generated by the SBFC.')
            os.remove(filename)
