
#
# This file is automatically generated with 
# the System Biology Format Converter (http://sbfc.sourceforge.net/)
# from an SBML file.
#
# The conversion system has the following limitations:
#  - You may have to re order some reactions and Assignment Rules definition
#  - Delays are not taken into account
#  - You should change the lsode parameters (start, end, steps) to get better results
#

#
# The following line is there to be sure that Octave think that this file 
# is a script and not function file
#
1;

#
# Model name = Clarke2000 - One-hit model of cell death in neuronal degenerations
#
# is http://identifiers.org/biomodels.db/MODEL1408070000
# is http://identifiers.org/biomodels.db/BIOMD0000000538
# isDescribedBy http://identifiers.org/pubmed/10910361
#
function z=pow(x,y),z=x^y;endfunction
function z=root(x,y),z=y^(1/x);endfunction
function z = piecewise(varargin)
	numArgs = nargin;
	result = 0;
	foundResult = 0;
	for k=1:2: numArgs-1
		if varargin{k+1} == 1
			result = varargin{k};
			foundResult = 1;
			break;
		endif
	end
	if foundResult == 0
		result = varargin{numArgs};
	endif
z = result;
endfunction

function xdot=f(x,t)
# Compartment: id = Brain, name = Brain, constant
	compartment_Brain=1.0;
# Parameter:   id =  Munr, name = Munr
	global_par_Munr=0.278;
# Parameter:   id =  Mupcd, name = Mupcd
	global_par_Mupcd=0.223;
# Parameter:   id =  Rrom, name = Rrom
	global_par_Rrom=0.103;
# Parameter:   id =  ONLrom_0, name = ONLrom
	global_par_ONLrom_0=40.947;
# Parameter:   id =  Murom, name = Murom
	global_par_Murom=0.0708;
# assignmentRule: variable = ONLrom
	x(3)=global_par_ONLrom_0*exp((exp((-global_par_Rrom)*time)-1)*global_par_Murom/global_par_Rrom)*100/global_par_ONLrom_0;
# rateRule: variable = ONLnr
x(1) = x(4);
# rateRule: variable = ONLpcd
x(2) = x(5);
	xdot=zeros(5,1);
	# rateRule: variable = ONLnr
	xdot(4) = (-global_par_Munr)*x(1);

	# rateRule: variable = ONLpcd
	xdot(5) = (-global_par_Mupcd)*x(2);

	# Species:   id = ONLnr, name = ONLnr, involved in a rule 
	xdot(1) = x(1);

	# Species:   id = ONLpcd, name = ONLpcd, involved in a rule 
	xdot(2) = x(2);

	# Species:   id = ONLrom, name = ONLrom, involved in a rule 
	xdot(3) = x(3);

endfunction

#Initial conditions vector
x0=zeros(5,1);
x0(4) = NaN;
x0(5) = NaN;
x0(1) = 100.0;
x0(2) = 100.0;
x0(3) = 100.0;


#Creating linespace
t=linspace(0,90,100);

#Solving equations
x=lsode("f",x0,t);

#ploting the results
plot(t,x);
