
#
# This file is automatically generated with 
# the System Biology Format Converter (http://sbfc.sourceforge.net/)
# from an SBML file.
#
# The conversion system has the following limitations:
#  - You may have to re order some reactions and Assignment Rules definition
#  - Delays are not taken into account
#  - You should change the lsode parameters (start, end, steps) to get better results
#

#
# The following line is there to be sure that Octave think that this file 
# is a script and not function file
#
1;

#
# Model name = Vazquez2014 - Chemical inhibition from amyloid protein aggregation kinetics
#
# is http://identifiers.org/biomodels.db/MODEL1407300000
# is http://identifiers.org/biomodels.db/BIOMD0000000532
# isDescribedBy http://identifiers.org/pubmed/24572069
#
function z=pow(x,y),z=x^y;endfunction
function z=root(x,y),z=y^(1/x);endfunction
function z = piecewise(varargin)
	numArgs = nargin;
	result = 0;
	foundResult = 0;
	for k=1:2: numArgs-1
		if varargin{k+1} == 1
			result = varargin{k};
			foundResult = 1;
			break;
		endif
	end
	if foundResult == 0
		result = varargin{numArgs};
	endif
z = result;
endfunction

function xdot=f(x,t)
# Compartment: id = cell, name = cell, constant
	compartment_cell=1.0;
# Parameter:   id =  xm, name = xm
	global_par_xm=1.0;
# Parameter:   id =  vm, name = vm
	global_par_vm=0.25;
# Parameter:   id =  lambda, name = lambda
	global_par_lambda=3.0;
# Parameter:   id =  kx, name = kx
	global_par_kx=1.0;
# Parameter:   id =  mx, name = mx
	global_par_mx=5.0;
# Parameter:   id =  ax, name = ax
	global_par_ax=2.0;
# Parameter:   id =  kv, name = kv
	global_par_kv=1.0;
# Parameter:   id =  mv, name = mv
	global_par_mv=4.0;
# Parameter:   id =  av, name = av
	global_par_av=2.0;
# Parameter:   id =  klambda, name = klambda
	global_par_klambda=1.0;
# Parameter:   id =  mlambda, name = mlambda
	global_par_mlambda=2.0;
# Parameter:   id =  alambda, name = alambda
	global_par_alambda=2.0;
# Parameter:   id =  C, name = C
	global_par_C=1.0;
# assignmentRule: variable = X
	x(1)=x(2)/(1+exp(2+4*x(3)/x(2)*(x(4)-time)));
	xdot=zeros(4,1);
	# Species:   id = X, name = X, involved in a rule 
	xdot(1) = x(1);

	# Species:   id = Xm, name = Xm, involved in a rule 
	xdot(2) = x(2);

	# Species:   id = Vm, name = Vm, involved in a rule 
	xdot(3) = x(3);

	# Species:   id = Lambda, name = Lambda, involved in a rule 
	xdot(4) = x(4);

endfunction

#Initial conditions vector
x0=zeros(4,1);
x0(1) = 0.00427219370168501;
x0(2) = 0.972654947412286;
x0(3) = 0.239400820174643;
x0(4) = 3.47731075423886;


#Creating linespace
t=linspace(0,90,100);

#Solving equations
x=lsode("f",x0,t);

#ploting the results
plot(t,x);
