
#
# This file is automatically generated with 
# the System Biology Format Converter (http://sbfc.sourceforge.net/)
# from an SBML file.
#
# The conversion system has the following limitations:
#  - You may have to re order some reactions and Assignment Rules definition
#  - Delays are not taken into account
#  - You should change the lsode parameters (start, end, steps) to get better results
#

#
# The following line is there to be sure that Octave think that this file 
# is a script and not function file
#
1;

#
# Model name = Crespo2012 - Kinetics of Amyloid Fibril Formation
#
# is http://identifiers.org/biomodels.db/MODEL1407170000
# is http://identifiers.org/biomodels.db/BIOMD0000000531
# isDescribedBy http://identifiers.org/pubmed/22767606
#
function z=pow(x,y),z=x^y;endfunction
function z=root(x,y),z=y^(1/x);endfunction
function z = piecewise(varargin)
	numArgs = nargin;
	result = 0;
	foundResult = 0;
	for k=1:2: numArgs-1
		if varargin{k+1} == 1
			result = varargin{k};
			foundResult = 1;
			break;
		endif
	end
	if foundResult == 0
		result = varargin{numArgs};
	endif
z = result;
endfunction

function xdot=f(x,t)
# Compartment: id = Cell, name = Cell, constant
	compartment_Cell=1.0;
# Parameter:   id =  Ka, name = Ka
	global_par_Ka=1.44;
# Parameter:   id =  kb, name = kb
	global_par_kb=1.6E-10;
# Parameter:   id =  kat50, name = kat50
# Parameter:   id =  v50t50, name = v50t50
# assignmentRule: variable = kat50
	global_par_kat50=log(1/global_par_kb+1);
# assignmentRule: variable = v50t50
	global_par_v50t50=1/4*(global_par_kb+1)*log(1/global_par_kb+1);
# assignmentRule: variable = alpha
	x(1)=1-1/(global_par_kb*(exp(global_par_Ka*time)-1)+1);
	xdot=zeros(1,1);
	# Species:   id = alpha, name = alpha, involved in a rule 
	xdot(1) = x(1);

endfunction

#Initial conditions vector
x0=zeros(1,1);
x0(1) = 0.0;


#Creating linespace
t=linspace(0,90,100);

#Solving equations
x=lsode("f",x0,t);

#ploting the results
plot(t,x);
