
#
# This file is automatically generated with 
# the System Biology Format Converter (http://sbfc.sourceforge.net/)
# from an SBML file.
#
# The conversion system has the following limitations:
#  - You may have to re order some reactions and Assignment Rules definition
#  - Delays are not taken into account
#  - You should change the lsode parameters (start, end, steps) to get better results
#

#
# The following line is there to be sure that Octave think that this file 
# is a script and not function file
#
1;

#
# Model name = Raman2006_MycolicAcid
#
# is urn:miriam:biomodels.db:MODEL8568434338
# isDescribedBy urn:miriam:pubmed:16261191
#

#
# The model cannot be converted as there are some kineticLaw undefined.
#

